version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leave-api
    ports:
      - "8080:80"
    volumes:
      - ./leave.db:/app/leave.db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
